"""Render this warehouse's bus matrix into `docs/WAREHOUSE.md`.

The derivation is `modern_data_stack.bus_matrix`, which knows nothing about this
project. Here live the constants: which schema holds the published layer, and
which holes in the matrix are already known.

**Why `publish/` and not `scripts/`.** `scripts/` is for the genuinely one-off,
and this is the opposite — it must run again every time a mart is added or a key
renamed, or the block it writes becomes another stale list. It sits beside
`build_report.py`, which already turns the manifest into something outward-facing
and holds `TABLE_TO_DBT_MODEL` for the same reason this holds `KNOWN_UNCONFORMED`.

**The declared holes are not an allowlist of things that are fine.** A hole is a
fact that joins to no conformed dimension, and the reason attached to it says
whether that is a boundary or a defect. Two are declared today and only one of
them is a decision — writing the other down is what stops it being rediscovered
by a survey a third time.
"""

from __future__ import annotations

import sys
from pathlib import Path

from modern_data_stack import bus_matrix
from modern_data_stack.paths import dbt_manifest_path, project_root

SCHEMA = "marts"

DOC_PATH = "docs/WAREHOUSE.md"
MARKER_BEGIN = "<!-- bus-matrix:begin -->"
MARKER_END = "<!-- bus-matrix:end -->"

# Facts that conform to no dimension at all, and why. `tests/test_bus_matrix.py`
# asserts this is exactly the set the manifest produces, in both directions — so
# a new orphan fails, and so does fixing one without deleting its entry.
KNOWN_UNCONFORMED: dict[str, str] = {
    "fct_retail_customer_cohorts": (
        "Deliberate. An aggregate at `(cohort_month, months_since_first_order)`: "
        "the customer is aggregated away by construction, and `cohort_month` is a "
        "cohort label rather than a calendar day, so there is no grain at which "
        "`dim_date` or `dim_retail_customer` could be joined."
    ),
    "fct_fx_rates_periods": (
        "**Open finding, not a boundary.** It carries `quote_currency` where "
        "`dim_currency` publishes `currency_code` — the same dimension under a "
        "second name, which its own sibling `fct_fx_rates_daily` spells the "
        "conformed way — and its four date columns are period bounds rather than "
        "`date_day` or `date_key`. Nothing about this model requires either."
    ),
}


def matrix() -> bus_matrix.BusMatrix:
    """The matrix for this warehouse's published layer."""
    return bus_matrix.build(dbt_manifest_path(), schema=SCHEMA)


def render(built: bus_matrix.BusMatrix | None = None) -> str:
    """The markdown block, markers included, ready to drop into the doc."""
    built = built or matrix()
    parts = [
        MARKER_BEGIN,
        "",
        "<!-- Generated by `just bus-matrix`. Do not edit between the markers. -->",
        "",
        bus_matrix.to_markdown(built),
        "",
    ]
    notes = bus_matrix.key_notes(built)
    if notes:
        parts += ["Notes:", "", *(f"- {note}" for note in notes), ""]
    if KNOWN_UNCONFORMED:
        parts += ["Facts conforming to no dimension:", ""]
        parts += [f"- `{fact}` — {why}" for fact, why in sorted(KNOWN_UNCONFORMED.items())]
        parts += [""]
    parts += [MARKER_END]
    return "\n".join(parts)


def write_doc(doc_path: str | Path | None = None) -> Path:
    """Replace the marked block in the doc, leaving everything around it alone.

    Refuses rather than appends when the markers are missing: a generator that
    silently adds a second copy of its own output is how a doc ends up with two
    matrices that disagree.
    """
    path = Path(doc_path) if doc_path else project_root() / DOC_PATH
    text = path.read_text()
    start, end = text.find(MARKER_BEGIN), text.find(MARKER_END)
    if start == -1 or end == -1:
        raise RuntimeError(f"{path} has no {MARKER_BEGIN} / {MARKER_END} block to fill")
    path.write_text(text[:start] + render() + text[end + len(MARKER_END) :])
    return path


def main() -> int:
    written = write_doc()
    built = matrix()
    print(
        f"wrote the bus matrix into {written}: "
        f"{len(built.facts)} facts x {len(built.dimensions)} conformed dimensions"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
